### ISSUE TITLE
does not compile on Linux Host

### ISSUE THREAD

**Issue by gianlucarenzi** [kaetemi/gdemu#1]
Hello,
I know this is a very old project, but I need to build up a Linux Gameduino v1 Emulator because I am building an hardware for retrocomputers to run gameduino on them, and for start I need a emulator on PC.
When compiling it gives me an error on the min() and max() MACROS, giving those errors:

n file included from /usr/include/c++/8/bits/char_traits.h:39,
                 from /usr/include/c++/8/string:40,
                 from /home/debian/packages/gdemu/gdemu/gdemu_system_sdl.h:53,
                 from /home/debian/packages/gdemu/gdemu/gdemu_graphics_driver_sdl.cpp:36:
/usr/include/c++/8/bits/stl_algobase.h:243:56: error: macro "min" passed 3 arguments, but takes just 2
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
                                                        ^
/usr/include/c++/8/bits/stl_algobase.h:265:56: error: macro "max" passed 3 arguments, but takes just 2
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
                                                       
Can you help me out to solve those issues?

Regards,

**Comment by kaetemi** [comment]
In "wiring.h", remove the min/max definitions, maybe need to replace with
using std::max;
using std::min;

--
Jan Boon

**Comment by gianlucarenzi** [comment]
On 10/07/2019 03:06 PM, Jan Boon wrote:
> In "wiring.h", remove the min/max definitions, maybe need to replace with
> using std::max;
> using std::min;
>

Adding the following:

#include <algorithm>    // std::min

using std::max;

using std::min;

helps to build the library correctly.

Now I have some warnings/errors compiling some examples, but I do not 
care. The library seems to work with Asteroids, Boing Ball and others...

Cheers

-- 
Eurek s.r.l.                          |
Electronic Engineering                | http://www.eurek.it
via Celletta 8/B, 40026 Imola, Italy  | Phone: +39-(0)542-609120
p.iva 00690621206 - c.f. 04020030377  | Fax:   +39-(0)542-609212
